export default function ErrorTest() {
  throw new Error('This is a forced error to test the error boundary!');
}
